<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-25 08:00

$extensionPath = t3lib_extMgm::extPath('flex');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_flex_controller_standardcontroller' => $extensionClassesPath . 'Controller/StandardController.php',
	'tx_flex_domain_model_layout' => $extensionClassesPath . 'Domain/Model/Layout.php',
	'tx_flex_domain_model_template' => $extensionClassesPath . 'Domain/Model/Template.php',
	'tx_flex_domain_repository_templaterepository' => $extensionClassesPath . 'Domain/Repository/TemplateRepository.php',
	'tx_flex_helper_tcahelper' => $extensionClassesPath . 'Helper/TcaHelper.php',
	'tx_flex_viewhelpers_plainviewhelper' => $extensionClassesPath . 'ViewHelpers/PlainViewHelper.php',
	'tx_flex_viewhelpers_typoscriptviewhelper' => $extensionClassesPath . 'ViewHelpers/TypoScriptViewHelper.php',
);
?>