<?php

########################################################################
# Extension Manager/Repository config file for ext: "flex"
#
# Auto generated by Extbase Kickstarter 2011-02-16
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Flex',
	'description' => 'Flexible Content Elements for Fluid',
	'category' => 'plugin',
	'author' => 'Rens Admiraal,Peter Beernink',
	'author_email' => 'r.admiraal@drecomm.nl,p.beernink@drecomm.nl',
	'author_company' => 'Drecomm Internet Intelligence',
	'shy' => '',
	'dependencies' => 'extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>